### ISSUE TITLE
Ajuste del código fuente a 100 columnas para mejorar la legibilidad

### ISSUE THREAD

**Issue by ibanezfr** [fernandodanielmaqueda/gcc-bison-flex-GNUmakefile#1]
## Propuesta:
   - Sugiero ajustar el código fuente del proyecto a `80, 100 o 120 columnas`, alli donde sea posible.
   - Esto mejorará la legibilidad, facilitando la colaboración y el mantenimiento del código.
   - Se podría empezar ajustando los comentarios, si el resultado final es agradable, se avanzaría con el ajuste de las líneas de instrucción, pero eso sería otro tema, puede que no sea posible partirlas en este caso, eso depende de cada lenguaje.

### Comentarios originales:
<img src="https://github.com/fernandodanielmaqueda/gcc-bison-flex-GNUmakefile/assets/98627998/3a0226b7-7e83-46dd-b242-7cd7df2249b3" alt="Comentarios originales" width="720" height="400">

### Comentarios ajustados a 100 columnas:
<img src="https://github.com/fernandodanielmaqueda/gcc-bison-flex-GNUmakefile/assets/98627998/a8d7cd64-2a9e-4cf8-ab74-f0cd0125c314" alt="Comentarios ajustados a 100 columnas" width="720" height="400">

**Comment by fernandodanielmaqueda** [comment]
¡Hola!
Gracias por tu comentario, lo tuve en cuenta para el commit d286423
¡Saludos!
